<?php
session_start();require_once('../dbclas/pdocls.php');header("Content-Type: application/json; charset=UTF-8");class User extends database{ public $result=array(); public $db; public function GETUL($tid){if(isset($_SESSION["UNM"])){$db=new User("root","","localhost","bitirmeproje");$userLayoutRows=$db->getrows("SELECT  * FROM layout
                    where tid=?",array($tid));if(count($userLayoutRows)==0){$this->result=array("status"=>"None");return $this->result;}else {for($i=0;$i<count($userLayoutRows);$i++){$this->result[]=array("status"=>"Okey","lid"=>$userLayoutRows[$i]['lid'],"lynm"=>$userLayoutRows[$i]['lynm'],"lyrouter"=>$userLayoutRows[$i]["lyrouter"],"tid"=>$userLayoutRows[$i]["tid"],);}return $this->result;}}} public function GET($name){if(isset($_SESSION["UNM"])){$db=new User("root","","localhost","bitirmeproje");$uLT=date("Y.m.d");$userRows=$db->getrows("SELECT  * FROM user u INNER JoIN title t 
        on u.tid=t.tid INNER JoIN authority a on u.uauthr=a.autid
        INNER JOIN useronsection us on us.uid=u.uid INNER JOIN sections sc on sc.sid=us.sid
            where unm=?",array($name));if(count($userRows)==0){$this->result=array("status"=>"None");return $this->result;}else {for($i=0;$i<count($userRows);$i++){$this->result[]=array("Status"=>"Okey","uid"=>$userRows[$i]['uid'],"ufnm"=>$userRows[$i]['ufnm'],"ulnm"=>$userRows[$i]["ulnm"],"unm"=>$userRows[$i]["unm"],"upnt"=>$userRows[$i]["upnt"],"usno"=>$userRows[$i]["usno"],"tid"=>$userRows[$i]["tid"],"uauthr"=>$userRows[$i]["uauthr"],"tnm"=>$userRows[$i]["tnm"],"autnm"=>$userRows[$i]["autnm"],"uLD"=>$uLT,"sid"=>$userRows[$i]["sid"],"sname"=>$userRows[$i]["sname"],);}return $this->result;}}} public function ADD($ufnm,$ulnm,$unm,$utel,$upnt,$usno,$upass,$sid,$tid,$uauthr,$email){if(isset($_SESSION["UNM"])){$db=new User("root","","localhost","bitirmeproje");$addRows=$db->ekle("INSERT INTO user 
    (ufnm,ulnm,upnt,usno,unm,tid,uauthr) values('$ufnm','$ulnm','$upnt','$usno','$unm','$tid','$uauthr')");if($addRows){$userRows=$db->getrows("SELECT  * FROM user  where unm=?",array($unm));$uid=$userRows[0]['uid'];$addpassRows=$db->ekle("INSERT INTO pass 
        (pass,uid) values('$upass',' $uid')");if($addpassRows){$addmailRows=$db->ekle("INSERT INTO mail 
            (mail,uid) values('$email',' $uid')");if($addmailRows){$addphoneRows=$db->ekle("INSERT INTO phone 
                (pnmbr,uid) values('$utel',' $uid')");if($addphoneRows){$addsectiononLessonRows=$db->ekle("INSERT INTO useronsection (uid,sid) values
                        ('$uid','$sid')");if($addsectiononLessonRows){$this->result=array("status"=>"SuccesAdd","uid"=>$uid);return $this->result;}else {$this->result=array("status"=>"None");return $this->result;}}else {$this->result=array("status"=>"None");return $this->result;}}else {$this->result=array("status"=>"None");return $this->result;}}else {$this->result=array("status"=>"None");return $this->result;}}else {$this->result=array("status"=>"None");return $this->result;}}} public function GAUW($uwhere,$uparam,$mwhere,$mparam,$pwhere,$pparam){if(isset($_SESSION["UNM"])){$db=new User("root","","localhost","bitirmeproje");$userWhereRows=$db->getrows("SELECT  * FROM user WHERE $uwhere",array($uparam));{if(count($userWhereRows)==0){$mailWhereRows=$db->getrows("SELECT  * FROM mail WHERE $mwhere",array($mparam));if(count($mailWhereRows)==0){$phoneWhereRows=$db->getrows("SELECT  * FROM phone WHERE $pwhere",array($pparam));if(count($phoneWhereRows)==0){$this->result=array("status"=>"None");return $this->result;}else {$this->result=array("status"=>"haveP");return $this->result;}}else {$this->result=array("status"=>"haveM");return $this->result;}}else {$this->result=array("status"=>"haveUNM");return $this->result;}}}}}?>